---
title: "Homework"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Handing in

Send your homework before the homework date to [martin.hinz\@unibe.ch](mailto:martin.hinz@unibe.ch).

+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework                                                                                                                               | Homework Date | Homework Data  |
+========================================================================================================================================+===============+================+
| Choose one of the following five groups and collect the data about the participants accordingly                                        | 24.2.2025     | not applicable |
|                                                                                                                                        |               |                |
| Data to collect for the groups                                                                                                         |               |                |
|                                                                                                                                        |               |                |
| A)  Email, number of the computer in front of you                                                                                      |               |                |
| B)  Gender, Age                                                                                                                        |               |                |
| C)  laptop yes/no, foot size                                                                                                           |               |                |
| D)  actual cash in your purse, height                                                                                                  |               |                |
| E)  homecountry, operation system used at home                                                                                         |               |                |
|                                                                                                                                        |               |                |
| Collect the data matrix, determine the level of measurement of each variable and send me your data collection via email until weekend. |               |                |
|                                                                                                                                        |               |                |
| Make it a group work! organise yourself! No one is an island!                                                                          |               |                |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework via interactive tutorial: <https://martinhinz.shinyapps.io/smada_homework02/>                                                 | 10.3.2025     | provided       |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework via interactive tutorial: <https://martinhinz.shinyapps.io/smada_homework03/>                                                 | 17.03.2025    | provided       |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework via interactive tutorial:\                                                                                                    | 01.04.2025    | provided       |
| <https://martinhinz.shinyapps.io/smada_homework04/>                                                                                    |               |                |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework via interactive tutorial:\                                                                                                    | 15.04.2025    | provided       |
| <https://martinhinz.shinyapps.io/smada_homework05/>                                                                                    |               |                |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
| Homework via interactive tutorial:\                                                                                                    | 29.04.2025    | provided       |
| <https://martinhinz.shinyapps.io/smada_homework06/>                                                                                    |               |                |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
|                                                                                                                                        |               |                |
+----------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------+
